language: node_js
node_js:
- '0.10'
services:
- mongodb
before_install:
- npm install -g grunt-cli
script: npm test && grunt test-functional
deploy:
  provider: heroku
  api_key: d24a23ad-3c56-4491-b885-9ab54de40c55
  app: selfiequest-dev
env:
  global:
  - secure: PMgwqguoLU50daSh2ogsywNBHprAubElsgS87CMnX7WttjThPmc8OVECO1LNdQ539q5p3b1qXDYdXW00QfiPEdYNmYj8g4JqNJVgE9/MasxQWtFrSetu5Fdn+gVQA7v6cXG6PBGAQl8ZDaJI3HYMUwaM6Oo2cPY+qT2qoOQgN+E=
  - secure: UQudL6KJv6BYlUdE0amT/V890g5/hCdE53HMi367wRNwtmG/3G+qw8k/P8wcCoCt+O4kgOQsj2wEYXMycok+rrn6w2+SJSFMbItKBygLVNq6/dg76Z4pzDypUee/frueziyR39siW4hOm2KweRQnimdLAtxWq0a/h2QdRasspm8=
  - secure: WMMQ6Jjo9DsiBaXnIpWVQfixGMVnHuE/Ih+zlvgpNAV4eLHOQWTEX6I05BWhVWmRxuwgJ6vMrb6eBEl4syPjNwEdXjO73B25dsL14nkkWod23wPLlsuzk1ICMVykbtwHQn6FJpwJbLqhDTXc8lJBQWMf3V/O0amRRi6Q0KZ6z+A=
  - secure: gEH6E7D2mw2NL289XXSiP0vDF7BHHIx7Vk1nHls0NZwsdyLOzOPw5n2tOrl+bdcfzN/tA8RvUogedxz6WBFnBufQA12zBe97QWGbOF249MpLgCct6YUnPVOTwFB7q6+5qVpjgOYvGCu4K85mMOJKn8/8FSAxOHSFp6/ghAzOK2s=
